/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { RecipeSource, UiMealPlanEntry, UiRecipeFormValue, UiRecipeSummary } from "./type";
import { FavoriteToggleDetail } from "./components/favorite-button/favorite-button";
import { MealAddDetail } from "./components/meal-plan-week/meal-plan-week";
import { RecipeClickDetail } from "./components/recipe-card/recipe-card";
import { FavoriteToggleDetail as FavoriteToggleDetail1 } from "./components/favorite-button/favorite-button";
import { RecipeFilterValue } from "./components/recipe-filter/recipe-filter";
import { RecipeClickDetail as RecipeClickDetail1 } from "./components/recipe-card/recipe-card";
export { RecipeSource, UiMealPlanEntry, UiRecipeFormValue, UiRecipeSummary } from "./type";
export { FavoriteToggleDetail } from "./components/favorite-button/favorite-button";
export { MealAddDetail } from "./components/meal-plan-week/meal-plan-week";
export { RecipeClickDetail } from "./components/recipe-card/recipe-card";
export { FavoriteToggleDetail as FavoriteToggleDetail1 } from "./components/favorite-button/favorite-button";
export { RecipeFilterValue } from "./components/recipe-filter/recipe-filter";
export { RecipeClickDetail as RecipeClickDetail1 } from "./components/recipe-card/recipe-card";
export namespace Components {
    interface ConfirmationDialog {
        /**
          * @default 'Cancel'
         */
        "cancelLabel": string;
        /**
          * @default 'Delete'
         */
        "confirmLabel": string;
        /**
          * @default 'Are you sure?'
         */
        "heading": string;
        /**
          * @default 'This action cannot be undone'
         */
        "message": string;
        /**
          * @default false
         */
        "open": boolean;
    }
    interface FavoriteButton {
        /**
          * @default false
         */
        "active": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        "recipeId": string;
        /**
          * @default 'external'
         */
        "source": RecipeSource;
    }
    interface MealPlanCard {
        "entry": UiMealPlanEntry;
    }
    interface MealPlanWeek {
        /**
          * @default []
         */
        "meals": UiMealPlanEntry[];
        /**
          * @default ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
         */
        "week": string[];
    }
    interface ModalDialog {
        /**
          * @default false
         */
        "open": boolean;
    }
    interface RecipeCard {
        /**
          * @default false
         */
        "favorite": boolean;
        "recipe": UiRecipeSummary;
        /**
          * @default false
         */
        "showActions": boolean;
        /**
          * @default true
         */
        "showAuthor": boolean;
    }
    interface RecipeFilter {
        /**
          * @default ''
         */
        "area": string;
        /**
          * @default []
         */
        "areas": string[];
        /**
          * @default []
         */
        "categories": string[];
        /**
          * @default ''
         */
        "category": string;
        /**
          * @default true
         */
        "showMine": boolean;
        /**
          * @default 'all'
         */
        "source": RecipeFilterValue['source'];
    }
    interface RecipeForm {
        /**
          * @default []
         */
        "areas": string[];
        /**
          * @default []
         */
        "categories": string[];
        /**
          * @default 'create'
         */
        "mode": 'create' | 'edit';
        "recipe"?: UiRecipeFormValue;
        /**
          * @default false
         */
        "submitting": boolean;
    }
    interface RecipeGrid {
        /**
          * @default 'Try adjusting your search or filters.'
         */
        "emptyMessage": string;
        /**
          * Set of "source:id" strings that are currently favorited
          * @default []
         */
        "favorites": string[];
        /**
          * @default false
         */
        "loading": boolean;
        /**
          * @default []
         */
        "recipes": UiRecipeSummary[];
        /**
          * @default false
         */
        "showActions": boolean;
    }
    interface RecipeSearch {
        /**
          * @default 350
         */
        "debounce": number;
        /**
          * @default 'Search recipes…'
         */
        "placeholder": string;
        /**
          * @default ''
         */
        "value": string;
    }
}
export interface ConfirmationDialogCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLConfirmationDialogElement;
}
export interface FavoriteButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFavoriteButtonElement;
}
export interface MealPlanCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMealPlanCardElement;
}
export interface MealPlanWeekCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMealPlanWeekElement;
}
export interface ModalDialogCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModalDialogElement;
}
export interface RecipeCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeCardElement;
}
export interface RecipeFilterCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeFilterElement;
}
export interface RecipeFormCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeFormElement;
}
export interface RecipeGridCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeGridElement;
}
export interface RecipeSearchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeSearchElement;
}
declare global {
    interface HTMLConfirmationDialogElementEventMap {
        "confirm": void;
        "cancel": void;
    }
    interface HTMLConfirmationDialogElement extends Components.ConfirmationDialog, HTMLStencilElement {
        addEventListener<K extends keyof HTMLConfirmationDialogElementEventMap>(type: K, listener: (this: HTMLConfirmationDialogElement, ev: ConfirmationDialogCustomEvent<HTMLConfirmationDialogElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLConfirmationDialogElementEventMap>(type: K, listener: (this: HTMLConfirmationDialogElement, ev: ConfirmationDialogCustomEvent<HTMLConfirmationDialogElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLConfirmationDialogElement: {
        prototype: HTMLConfirmationDialogElement;
        new (): HTMLConfirmationDialogElement;
    };
    interface HTMLFavoriteButtonElementEventMap {
        "favorite-toggle": FavoriteToggleDetail;
    }
    interface HTMLFavoriteButtonElement extends Components.FavoriteButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFavoriteButtonElementEventMap>(type: K, listener: (this: HTMLFavoriteButtonElement, ev: FavoriteButtonCustomEvent<HTMLFavoriteButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFavoriteButtonElementEventMap>(type: K, listener: (this: HTMLFavoriteButtonElement, ev: FavoriteButtonCustomEvent<HTMLFavoriteButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFavoriteButtonElement: {
        prototype: HTMLFavoriteButtonElement;
        new (): HTMLFavoriteButtonElement;
    };
    interface HTMLMealPlanCardElementEventMap {
        "meal-edit": UiMealPlanEntry;
        "meal-remove": UiMealPlanEntry;
    }
    interface HTMLMealPlanCardElement extends Components.MealPlanCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMealPlanCardElementEventMap>(type: K, listener: (this: HTMLMealPlanCardElement, ev: MealPlanCardCustomEvent<HTMLMealPlanCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMealPlanCardElementEventMap>(type: K, listener: (this: HTMLMealPlanCardElement, ev: MealPlanCardCustomEvent<HTMLMealPlanCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMealPlanCardElement: {
        prototype: HTMLMealPlanCardElement;
        new (): HTMLMealPlanCardElement;
    };
    interface HTMLMealPlanWeekElementEventMap {
        "meal-add": MealAddDetail;
        "meal-edit": UiMealPlanEntry;
        "meal-remove": UiMealPlanEntry;
    }
    interface HTMLMealPlanWeekElement extends Components.MealPlanWeek, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMealPlanWeekElementEventMap>(type: K, listener: (this: HTMLMealPlanWeekElement, ev: MealPlanWeekCustomEvent<HTMLMealPlanWeekElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMealPlanWeekElementEventMap>(type: K, listener: (this: HTMLMealPlanWeekElement, ev: MealPlanWeekCustomEvent<HTMLMealPlanWeekElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMealPlanWeekElement: {
        prototype: HTMLMealPlanWeekElement;
        new (): HTMLMealPlanWeekElement;
    };
    interface HTMLModalDialogElementEventMap {
        "modal-close": void;
    }
    interface HTMLModalDialogElement extends Components.ModalDialog, HTMLStencilElement {
        addEventListener<K extends keyof HTMLModalDialogElementEventMap>(type: K, listener: (this: HTMLModalDialogElement, ev: ModalDialogCustomEvent<HTMLModalDialogElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLModalDialogElementEventMap>(type: K, listener: (this: HTMLModalDialogElement, ev: ModalDialogCustomEvent<HTMLModalDialogElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLModalDialogElement: {
        prototype: HTMLModalDialogElement;
        new (): HTMLModalDialogElement;
    };
    interface HTMLRecipeCardElementEventMap {
        "recipe-click": RecipeClickDetail;
        "favorite-toggle": FavoriteToggleDetail1;
        "recipe-edit": RecipeClickDetail;
        "recipe-delete": RecipeClickDetail;
    }
    interface HTMLRecipeCardElement extends Components.RecipeCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeCardElementEventMap>(type: K, listener: (this: HTMLRecipeCardElement, ev: RecipeCardCustomEvent<HTMLRecipeCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeCardElementEventMap>(type: K, listener: (this: HTMLRecipeCardElement, ev: RecipeCardCustomEvent<HTMLRecipeCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeCardElement: {
        prototype: HTMLRecipeCardElement;
        new (): HTMLRecipeCardElement;
    };
    interface HTMLRecipeFilterElementEventMap {
        "filter-change": RecipeFilterValue;
    }
    interface HTMLRecipeFilterElement extends Components.RecipeFilter, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeFilterElementEventMap>(type: K, listener: (this: HTMLRecipeFilterElement, ev: RecipeFilterCustomEvent<HTMLRecipeFilterElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeFilterElementEventMap>(type: K, listener: (this: HTMLRecipeFilterElement, ev: RecipeFilterCustomEvent<HTMLRecipeFilterElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeFilterElement: {
        prototype: HTMLRecipeFilterElement;
        new (): HTMLRecipeFilterElement;
    };
    interface HTMLRecipeFormElementEventMap {
        "recipe-submit": UiRecipeFormValue;
        "recipe-cancel": void;
    }
    interface HTMLRecipeFormElement extends Components.RecipeForm, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeFormElementEventMap>(type: K, listener: (this: HTMLRecipeFormElement, ev: RecipeFormCustomEvent<HTMLRecipeFormElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeFormElementEventMap>(type: K, listener: (this: HTMLRecipeFormElement, ev: RecipeFormCustomEvent<HTMLRecipeFormElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeFormElement: {
        prototype: HTMLRecipeFormElement;
        new (): HTMLRecipeFormElement;
    };
    interface HTMLRecipeGridElementEventMap {
        "recipe-click": RecipeClickDetail1;
        "favorite-toggle": FavoriteToggleDetail1;
        "recipe-edit": RecipeClickDetail1;
        "recipe-delete": RecipeClickDetail1;
    }
    interface HTMLRecipeGridElement extends Components.RecipeGrid, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeGridElementEventMap>(type: K, listener: (this: HTMLRecipeGridElement, ev: RecipeGridCustomEvent<HTMLRecipeGridElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeGridElementEventMap>(type: K, listener: (this: HTMLRecipeGridElement, ev: RecipeGridCustomEvent<HTMLRecipeGridElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeGridElement: {
        prototype: HTMLRecipeGridElement;
        new (): HTMLRecipeGridElement;
    };
    interface HTMLRecipeSearchElementEventMap {
        "search": string;
    }
    interface HTMLRecipeSearchElement extends Components.RecipeSearch, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeSearchElementEventMap>(type: K, listener: (this: HTMLRecipeSearchElement, ev: RecipeSearchCustomEvent<HTMLRecipeSearchElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeSearchElementEventMap>(type: K, listener: (this: HTMLRecipeSearchElement, ev: RecipeSearchCustomEvent<HTMLRecipeSearchElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeSearchElement: {
        prototype: HTMLRecipeSearchElement;
        new (): HTMLRecipeSearchElement;
    };
    interface HTMLElementTagNameMap {
        "confirmation-dialog": HTMLConfirmationDialogElement;
        "favorite-button": HTMLFavoriteButtonElement;
        "meal-plan-card": HTMLMealPlanCardElement;
        "meal-plan-week": HTMLMealPlanWeekElement;
        "modal-dialog": HTMLModalDialogElement;
        "recipe-card": HTMLRecipeCardElement;
        "recipe-filter": HTMLRecipeFilterElement;
        "recipe-form": HTMLRecipeFormElement;
        "recipe-grid": HTMLRecipeGridElement;
        "recipe-search": HTMLRecipeSearchElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K]?: never };

    interface ConfirmationDialog {
        /**
          * @default 'Cancel'
         */
        "cancelLabel"?: string;
        /**
          * @default 'Delete'
         */
        "confirmLabel"?: string;
        /**
          * @default 'Are you sure?'
         */
        "heading"?: string;
        /**
          * @default 'This action cannot be undone'
         */
        "message"?: string;
        "onCancel"?: (event: ConfirmationDialogCustomEvent<void>) => void;
        "onConfirm"?: (event: ConfirmationDialogCustomEvent<void>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
    }
    interface FavoriteButton {
        /**
          * @default false
         */
        "active"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "onFavorite-toggle"?: (event: FavoriteButtonCustomEvent<FavoriteToggleDetail>) => void;
        "recipeId": string;
        /**
          * @default 'external'
         */
        "source"?: RecipeSource;
    }
    interface MealPlanCard {
        "entry": UiMealPlanEntry;
        "onMeal-edit"?: (event: MealPlanCardCustomEvent<UiMealPlanEntry>) => void;
        "onMeal-remove"?: (event: MealPlanCardCustomEvent<UiMealPlanEntry>) => void;
    }
    interface MealPlanWeek {
        /**
          * @default []
         */
        "meals"?: UiMealPlanEntry[];
        "onMeal-add"?: (event: MealPlanWeekCustomEvent<MealAddDetail>) => void;
        "onMeal-edit"?: (event: MealPlanWeekCustomEvent<UiMealPlanEntry>) => void;
        "onMeal-remove"?: (event: MealPlanWeekCustomEvent<UiMealPlanEntry>) => void;
        /**
          * @default ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
         */
        "week"?: string[];
    }
    interface ModalDialog {
        "onModal-close"?: (event: ModalDialogCustomEvent<void>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
    }
    interface RecipeCard {
        /**
          * @default false
         */
        "favorite"?: boolean;
        "onFavorite-toggle"?: (event: RecipeCardCustomEvent<FavoriteToggleDetail1>) => void;
        "onRecipe-click"?: (event: RecipeCardCustomEvent<RecipeClickDetail>) => void;
        "onRecipe-delete"?: (event: RecipeCardCustomEvent<RecipeClickDetail>) => void;
        "onRecipe-edit"?: (event: RecipeCardCustomEvent<RecipeClickDetail>) => void;
        "recipe": UiRecipeSummary;
        /**
          * @default false
         */
        "showActions"?: boolean;
        /**
          * @default true
         */
        "showAuthor"?: boolean;
    }
    interface RecipeFilter {
        /**
          * @default ''
         */
        "area"?: string;
        /**
          * @default []
         */
        "areas"?: string[];
        /**
          * @default []
         */
        "categories"?: string[];
        /**
          * @default ''
         */
        "category"?: string;
        "onFilter-change"?: (event: RecipeFilterCustomEvent<RecipeFilterValue>) => void;
        /**
          * @default true
         */
        "showMine"?: boolean;
        /**
          * @default 'all'
         */
        "source"?: RecipeFilterValue['source'];
    }
    interface RecipeForm {
        /**
          * @default []
         */
        "areas"?: string[];
        /**
          * @default []
         */
        "categories"?: string[];
        /**
          * @default 'create'
         */
        "mode"?: 'create' | 'edit';
        "onRecipe-cancel"?: (event: RecipeFormCustomEvent<void>) => void;
        "onRecipe-submit"?: (event: RecipeFormCustomEvent<UiRecipeFormValue>) => void;
        "recipe"?: UiRecipeFormValue;
        /**
          * @default false
         */
        "submitting"?: boolean;
    }
    interface RecipeGrid {
        /**
          * @default 'Try adjusting your search or filters.'
         */
        "emptyMessage"?: string;
        /**
          * Set of "source:id" strings that are currently favorited
          * @default []
         */
        "favorites"?: string[];
        /**
          * @default false
         */
        "loading"?: boolean;
        "onFavorite-toggle"?: (event: RecipeGridCustomEvent<FavoriteToggleDetail1>) => void;
        "onRecipe-click"?: (event: RecipeGridCustomEvent<RecipeClickDetail1>) => void;
        "onRecipe-delete"?: (event: RecipeGridCustomEvent<RecipeClickDetail1>) => void;
        "onRecipe-edit"?: (event: RecipeGridCustomEvent<RecipeClickDetail1>) => void;
        /**
          * @default []
         */
        "recipes"?: UiRecipeSummary[];
        /**
          * @default false
         */
        "showActions"?: boolean;
    }
    interface RecipeSearch {
        /**
          * @default 350
         */
        "debounce"?: number;
        "onSearch"?: (event: RecipeSearchCustomEvent<string>) => void;
        /**
          * @default 'Search recipes…'
         */
        "placeholder"?: string;
        /**
          * @default ''
         */
        "value"?: string;
    }

    interface ConfirmationDialogAttributes {
        "open": boolean;
        "heading": string;
        "message": string;
        "confirmLabel": string;
        "cancelLabel": string;
    }
    interface FavoriteButtonAttributes {
        "active": boolean;
        "recipeId": string;
        "source": RecipeSource;
        "disabled": boolean;
    }
    interface ModalDialogAttributes {
        "open": boolean;
    }
    interface RecipeCardAttributes {
        "favorite": boolean;
        "showAuthor": boolean;
        "showActions": boolean;
    }
    interface RecipeFilterAttributes {
        "source": RecipeFilterValue['source'];
        "category": string;
        "area": string;
        "showMine": boolean;
    }
    interface RecipeFormAttributes {
        "mode": 'create' | 'edit';
        "submitting": boolean;
    }
    interface RecipeGridAttributes {
        "loading": boolean;
        "showActions": boolean;
        "emptyMessage": string;
    }
    interface RecipeSearchAttributes {
        "value": string;
        "placeholder": string;
        "debounce": number;
    }

    interface IntrinsicElements {
        "confirmation-dialog": Omit<ConfirmationDialog, keyof ConfirmationDialogAttributes> & { [K in keyof ConfirmationDialog & keyof ConfirmationDialogAttributes]?: ConfirmationDialog[K] } & { [K in keyof ConfirmationDialog & keyof ConfirmationDialogAttributes as `attr:${K}`]?: ConfirmationDialogAttributes[K] } & { [K in keyof ConfirmationDialog & keyof ConfirmationDialogAttributes as `prop:${K}`]?: ConfirmationDialog[K] };
        "favorite-button": Omit<FavoriteButton, keyof FavoriteButtonAttributes> & { [K in keyof FavoriteButton & keyof FavoriteButtonAttributes]?: FavoriteButton[K] } & { [K in keyof FavoriteButton & keyof FavoriteButtonAttributes as `attr:${K}`]?: FavoriteButtonAttributes[K] } & { [K in keyof FavoriteButton & keyof FavoriteButtonAttributes as `prop:${K}`]?: FavoriteButton[K] } & OneOf<"recipeId", FavoriteButton["recipeId"], FavoriteButtonAttributes["recipeId"]>;
        "meal-plan-card": MealPlanCard;
        "meal-plan-week": MealPlanWeek;
        "modal-dialog": Omit<ModalDialog, keyof ModalDialogAttributes> & { [K in keyof ModalDialog & keyof ModalDialogAttributes]?: ModalDialog[K] } & { [K in keyof ModalDialog & keyof ModalDialogAttributes as `attr:${K}`]?: ModalDialogAttributes[K] } & { [K in keyof ModalDialog & keyof ModalDialogAttributes as `prop:${K}`]?: ModalDialog[K] };
        "recipe-card": Omit<RecipeCard, keyof RecipeCardAttributes> & { [K in keyof RecipeCard & keyof RecipeCardAttributes]?: RecipeCard[K] } & { [K in keyof RecipeCard & keyof RecipeCardAttributes as `attr:${K}`]?: RecipeCardAttributes[K] } & { [K in keyof RecipeCard & keyof RecipeCardAttributes as `prop:${K}`]?: RecipeCard[K] };
        "recipe-filter": Omit<RecipeFilter, keyof RecipeFilterAttributes> & { [K in keyof RecipeFilter & keyof RecipeFilterAttributes]?: RecipeFilter[K] } & { [K in keyof RecipeFilter & keyof RecipeFilterAttributes as `attr:${K}`]?: RecipeFilterAttributes[K] } & { [K in keyof RecipeFilter & keyof RecipeFilterAttributes as `prop:${K}`]?: RecipeFilter[K] };
        "recipe-form": Omit<RecipeForm, keyof RecipeFormAttributes> & { [K in keyof RecipeForm & keyof RecipeFormAttributes]?: RecipeForm[K] } & { [K in keyof RecipeForm & keyof RecipeFormAttributes as `attr:${K}`]?: RecipeFormAttributes[K] } & { [K in keyof RecipeForm & keyof RecipeFormAttributes as `prop:${K}`]?: RecipeForm[K] };
        "recipe-grid": Omit<RecipeGrid, keyof RecipeGridAttributes> & { [K in keyof RecipeGrid & keyof RecipeGridAttributes]?: RecipeGrid[K] } & { [K in keyof RecipeGrid & keyof RecipeGridAttributes as `attr:${K}`]?: RecipeGridAttributes[K] } & { [K in keyof RecipeGrid & keyof RecipeGridAttributes as `prop:${K}`]?: RecipeGrid[K] };
        "recipe-search": Omit<RecipeSearch, keyof RecipeSearchAttributes> & { [K in keyof RecipeSearch & keyof RecipeSearchAttributes]?: RecipeSearch[K] } & { [K in keyof RecipeSearch & keyof RecipeSearchAttributes as `attr:${K}`]?: RecipeSearchAttributes[K] } & { [K in keyof RecipeSearch & keyof RecipeSearchAttributes as `prop:${K}`]?: RecipeSearch[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "confirmation-dialog": LocalJSX.IntrinsicElements["confirmation-dialog"] & JSXBase.HTMLAttributes<HTMLConfirmationDialogElement>;
            "favorite-button": LocalJSX.IntrinsicElements["favorite-button"] & JSXBase.HTMLAttributes<HTMLFavoriteButtonElement>;
            "meal-plan-card": LocalJSX.IntrinsicElements["meal-plan-card"] & JSXBase.HTMLAttributes<HTMLMealPlanCardElement>;
            "meal-plan-week": LocalJSX.IntrinsicElements["meal-plan-week"] & JSXBase.HTMLAttributes<HTMLMealPlanWeekElement>;
            "modal-dialog": LocalJSX.IntrinsicElements["modal-dialog"] & JSXBase.HTMLAttributes<HTMLModalDialogElement>;
            "recipe-card": LocalJSX.IntrinsicElements["recipe-card"] & JSXBase.HTMLAttributes<HTMLRecipeCardElement>;
            "recipe-filter": LocalJSX.IntrinsicElements["recipe-filter"] & JSXBase.HTMLAttributes<HTMLRecipeFilterElement>;
            "recipe-form": LocalJSX.IntrinsicElements["recipe-form"] & JSXBase.HTMLAttributes<HTMLRecipeFormElement>;
            "recipe-grid": LocalJSX.IntrinsicElements["recipe-grid"] & JSXBase.HTMLAttributes<HTMLRecipeGridElement>;
            "recipe-search": LocalJSX.IntrinsicElements["recipe-search"] & JSXBase.HTMLAttributes<HTMLRecipeSearchElement>;
        }
    }
}
